### ISSUE TITLE
load panthrGraphics into panthrBase

### ISSUE THREAD

**Issue by vanh17** [PanthR/panthrBase#112]
Using browserify js

**Comment by vanh17** [comment]
@skiadas,
Do you know where is the bundle file to load panthrMath to panthrBase?

**Comment by vanh17** [comment]
Dear Dr. @skiadas,
And when you browserify js files inside panthrGraphics, do we need to browserify all the js inside the app directory or we just need to browserify other file instead. I guess the first way is correct.
Warmest,

**Comment by vanh17** [comment]
I did the first way and create a file in my repository call panthrGraphics_uglifyjs.js. I just do not know if I load it correctly or not, do we have any way to tests it>?
By the way, I think I will create the different html file call graphics_distribution for it.
Warmest,

**Comment by skiadas** [comment]
You should fork the project and create issues on your fork and commit your changes to your fork so you can point to them for discussion.

panthrMath is not loaded as a bundle into panthrBase, it is loaded as an AMD module.
